### PR TITLE
Fix a flutter API that is now removed in beta: `ButtonTheme.bar` -> `ButtonBarTheme`

### PR DESCRIPTION
**Pull request by tiholic**
Ref: https://api.flutter.dev/flutter/material/ButtonTheme/ButtonTheme.bar.html

### CODE REVIEW

**Comment by nstrelow** [comment]
Please merge this soon. THanks :D

**Review by nstrelow — APPROVED** [review]

**Comment by tiholic** [comment]
cc: @anicdh @khakan-ali @calebisstupid

**Comment by nstrelow** [comment]
Please merge this, this package is used by other packages who do not have the time to migrate to a new package or use the flutter native functions.

flutter_form_builder is one example

**Comment by tiholic** [comment]
@nstrelow you could use `dependency_overrides` as a workaround for time being.

**Comment by nstrelow** [comment]
I am doing that, but I hate it.

The maintainer could just click 3 buttons and merge this

**Comment by anicdh** [comment]
I've merged. Sorry for this inconvenience :'(

**Pull request merged**
